### ISSUE TITLE
Process killed for some datasets

### ISSUE THREAD

**Issue by nishpatel96** [RonaldSun/VI-Stereo-DSO#17]
Hi Ronald,

For some datasets, for example EuroC V1_01_easy, the program works quite well for around 2000 frames but then suddenly gets killed.

These are the errors I get before and after using gdb. The errors do not occur at any specific point and I am not sure why the program gets killed.
![Error1](https://user-images.githubusercontent.com/47608418/62529513-14a02200-b83f-11e9-8079-2f742130d659.png)
![Error2](https://user-images.githubusercontent.com/47608418/62529514-14a02200-b83f-11e9-918b-878cb36f438d.png)

Do you have an idea what the problem could be in this case?

**Comment by nishpatel96** [comment]
Update:
It's an "Out of Memory" error but I am not able to point out what part of the code could be leading to this

**Comment by RonaldSun** [comment]
I did not encounter this problem. You'd better watch the memory usage. It may be due to insufficient memory.

**Comment by nishpatel96** [comment]
Yes, it is a memory issue. What was the RAM size on the PC you used to run this program?

**Comment by RonaldSun** [comment]
8GB
