### ISSUE TITLE
Stereo vision

### ISSUE THREAD

**Issue by EverettWang** [RonaldSun/VI-Stereo-DSO#22]
Dear Dr. Sun,

I have tried the software on both MH_01_easy and V2_03_difficult. The code works very well. But I saw a line print to the screen that 

...
"Out: Failed to Read Baseline... can not do stereo."
...

Does it mean the code is running in mono mode? If so, how to make it into stereo mode?

Best regards.

Everett

**Comment by RonaldSun** [comment]
No, that's remnant of the old version. Baseline is useless in current code.
