### ISSUE TITLE
Alignment with Ground Truth

### ISSUE THREAD

**Issue by RongenC** [RonaldSun/VI-Stereo-DSO#7]
I see that when you initialize the FirstFrame IMU (FullSystem::initFirstFrame_imu), you aligned the system with the ground truth. Does this mean that the current version of code does not able to align itself to world ground with the use of IMU data?

**Comment by RonaldSun** [comment]
Yes, of course. Alignment can be achieved knowing the location of the first frame.

**Comment by RongenC** [comment]
What if you do not know the first frame's location (i.e. initial true world xyz)? Gravity Direction can be retrieved directly from IMU's data right?

**Comment by RonaldSun** [comment]
Actually the location of first frame is set to (0,0,0). The "T_WR_align" is used to align the groundtruth to the system. So there will be a transformation between DSO's pose and world pose.

**Comment by RongenC** [comment]
Yes, so my question is if there is no groundtruth available for the first
frame, this system unable to locate it's starting location (mainly height
is relevant in this case)?

**Comment by RonaldSun** [comment]
Unable to lacate it's starting location

**Comment by RongenC** [comment]
Thank you for the clarification!
